version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_portaly
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
